/**
 * 헤아림 - 표현 해석 DB 2차 확장 (32종 추가)
 * data-extra.js 로드 후 HEARIM_DB에 push
 * 총합: 68(기존) + 32(추가) = 100종
 *
 * 카테고리:
 * 15. 연락·시간 표현
 * 16. 감정 직접 표현
 * 17. 관계 불안·확인
 * 18. 기대·설렘 표현
 * 19. 경계·거절 간접 표현
 * 20. 일상 안부·케어 표현
 */
(function () {

window.HEARIM_DB.push(

  /* ── 15. 연락·시간 표현 ─────────────────────────────── */
  {
    keys: ['심심해', '심심하다', '할 게 없어', '너무 심심해'],
    relation: ['lover','some','friend'],
    surface: '지루함 표현',
    hidden: '상대가 생각나서 연락한 것. 같이 있고 싶다는 신호',
    possibilities: [{label:'같이 있고 싶음',pct:55},{label:'단순 심심함',pct:30},{label:'관심 확인',pct:15}],
    emotions: ['💗 보고싶음','😊 연결원함'],
    action: '같이 뭔가 하거나 만날 것을 자연스럽게 제안해보세요.',
    confidence: 72,
    replies: [
      {style:'공감',text:'나도 심심해. 뭐 하고 있어?'},
      {style:'다정',text:'심심하면 나한테 연락해야지 :) 뭐 할까?'},
      {style:'유머',text:'심심하다고? 그럼 나랑 놀아야지 ㅋㅋ'},
      {style:'썸',text:'심심하면 나 보러 와도 되는데? ㅎㅎ'},
    ],
    tip: '심심하다는 말에 무관심하게 반응하면 상대가 서운해질 수 있어요.',
  },
  {
    keys: ['어디야', '지금 어디야', '지금 어디 있어', '어디서'],
    relation: ['lover','some','friend'],
    surface: '위치 확인',
    hidden: '만나고 싶거나 안부가 궁금한 것. 관심의 표현',
    possibilities: [{label:'만나고 싶음',pct:45},{label:'걱정·안부',pct:35},{label:'단순 궁금증',pct:20}],
    emotions: ['💗 관심','😊 보고싶음'],
    action: '위치를 알려주고 상대의 상황도 물어보세요.',
    confidence: 68,
    replies: [
      {style:'공감',text:'집이야~ 너는 어디야?'},
      {style:'다정',text:'카페에 있어. 왜? 오려고?'},
      {style:'유머',text:'너 어딘지 알면서 왜 물어봐 ㅋㅋ 집이야'},
      {style:'썸',text:'아직 ○○에 있어. 너 근처야? ㅎㅎ'},
    ],
    tip: '어디냐고 묻는 건 상대를 신경 쓰고 있다는 표시예요.',
  },
  {
    keys: ['기다려', '조금만 기다려', '곧 연락할게', '이따 연락할게'],
    relation: ['lover','some','friend'],
    surface: '잠시 대기 요청',
    hidden: '관계를 끊으려는 게 아닌, 상황이 생긴 것. 기다려줘도 됨',
    possibilities: [{label:'실제 바쁨',pct:60},{label:'마음의 여유 필요',pct:30},{label:'대화 부담',pct:10}],
    emotions: ['😐 바쁨','💗 연결유지'],
    action: '"알겠어, 기다릴게" 하고 편하게 기다려주세요.',
    confidence: 70,
    replies: [
      {style:'공감',text:'응 기다릴게. 연락 와도 돼 :)'},
      {style:'다정',text:'천천히 해. 기다릴게'},
      {style:'유머',text:'기다리는 거 잘 못하는데 ㅋㅋ 빨리 와'},
      {style:'썸',text:'알겠어 :) 기다리고 있을게'},
    ],
    tip: '기다리라는 말을 무시하고 계속 연락하면 역효과예요.',
  },
  {
    keys: ['늦겠어', '조금 늦을 것 같아', '미안 늦어', '10분만 기다려'],
    relation: ['lover','some','friend'],
    surface: '지각 예고',
    hidden: '상대를 기다리게 해서 미안한 마음. 배려의 표현',
    possibilities: [{label:'진짜 지각',pct:70},{label:'배려 연락',pct:25},{label:'약속 부담',pct:5}],
    emotions: ['😅 미안함','💗 배려'],
    action: '"괜찮아, 기다릴게" 하고 여유 있게 받아주세요.',
    confidence: 75,
    replies: [
      {style:'공감',text:'괜찮아~ 천천히 와. 기다릴게'},
      {style:'다정',text:'알겠어 :) 조심해서 와'},
      {style:'유머',text:'또야? ㅋㅋ 이번엔 진짜야?'},
      {style:'썸',text:'괜찮아. 기다리는 동안 네 생각할게 ㅎㅎ'},
    ],
    tip: '늦는다고 미리 연락하는 것 자체가 상대를 소중히 여기는 마음이에요.',
  },

  /* ── 16. 감정 직접 표현 ─────────────────────────────── */
  {
    keys: ['보고 싶어', '보고싶다', '보고 싶은데', '너무 보고 싶어'],
    relation: ['lover','some','friend'],
    surface: '그리움 표현',
    hidden: '강한 감정과 애정의 직접 표현. 즉시 따뜻하게 받아줘야 해요',
    possibilities: [{label:'진심으로 보고싶음',pct:75},{label:'관심 확인',pct:15},{label:'감정 표현 연습',pct:10}],
    emotions: ['💗 그리움','🥰 애정'],
    action: '같은 감정으로 받아주고 가능하다면 만남을 제안하세요.',
    confidence: 88,
    replies: [
      {style:'공감',text:'나도 보고 싶어ㅠ 언제 봐?'},
      {style:'다정',text:'나도 보고 싶었어 :) 이번 주에 볼까?'},
      {style:'유머',text:'보고 싶다고? 그럼 보러 와~ ㅋㅋ'},
      {style:'썸',text:'나도 보고 싶었어. 이번 주말 어때?'},
    ],
    tip: '"나도"라고 받아주는 게 관계를 가장 빠르게 따뜻하게 만들어요.',
  },
  {
    keys: ['행복해', '행복하다', '너무 행복해', '요즘 행복한 것 같아'],
    relation: ['lover','some','friend'],
    surface: '긍정적 감정 공유',
    hidden: '상대와 함께여서 행복하다는 암시. 관계에 만족하고 있음',
    possibilities: [{label:'관계에 만족',pct:55},{label:'일상 행복 공유',pct:35},{label:'상대 반응 기대',pct:10}],
    emotions: ['🥰 행복','💗 만족'],
    action: '함께 행복하다고 공감하고, 이유를 물어봐도 좋아요.',
    confidence: 80,
    replies: [
      {style:'공감',text:'나도! 요즘 진짜 좋아 :)'},
      {style:'다정',text:'그래서 다행이야. 왜 행복해?'},
      {style:'유머',text:'행복해? 혹시 내 덕분이야? ㅋㅋ'},
      {style:'썸',text:'행복하다니 나도 좋다. 나 때문이야? ㅎㅎ'},
    ],
    tip: '행복하다는 말에 "나도 덕분이야"라고 받으면 관계가 깊어져요.',
  },
  {
    keys: ['자꾸 생각나', '계속 생각나', '오늘 자꾸 떠오르네', '갑자기 생각났어'],
    relation: ['lover','some'],
    surface: '상대가 생각난다',
    hidden: '감정을 조심스럽게 고백하는 방식. 관심이 깊음',
    possibilities: [{label:'호감·그리움',pct:65},{label:'감정 확인 시도',pct:25},{label:'단순 연락',pct:10}],
    emotions: ['💗 그리움','🥰 설렘'],
    action: '따뜻하게 받아주고 비슷한 감정을 자연스럽게 표현해보세요.',
    confidence: 82,
    replies: [
      {style:'공감',text:'나도 네 생각 하고 있었어'},
      {style:'다정',text:'그래서 연락했어? 반갑다 :)'},
      {style:'유머',text:'왜 자꾸 생각나는 거야? 그게 뭔 뜻인지 알지? ㅎㅎ'},
      {style:'썸',text:'나도 사실 자꾸 생각나. 어쩌지 :)'},
    ],
    tip: '자꾸 생각난다는 말은 용기 내어 꺼낸 말이에요. 소중하게 받아주세요.',
  },
  {
    keys: ['미워', '미워요', '진짜 미워', '조금 미워'],
    relation: ['lover','some','friend'],
    surface: '밉다고 표현',
    hidden: '오히려 좋아한다는 뜻인 경우가 대부분. 친밀함의 역설적 표현',
    possibilities: [{label:'애정의 역설 표현',pct:60},{label:'가벼운 불만',pct:30},{label:'진짜 서운함',pct:10}],
    emotions: ['💗 애정','😤 가벼운 삐짐'],
    action: '"왜 미워? 나 잘못한 거 있어?" 하고 가볍게 물어보세요.',
    confidence: 70,
    replies: [
      {style:'공감',text:'왜 미워? 내가 뭔가 잘못했어?'},
      {style:'다정',text:'미워도 돼. 근데 나는 안 미워 :)'},
      {style:'유머',text:'미워? 그럼 더 귀엽게 굴어야겠다 ㅋㅋ'},
      {style:'썸',text:'미운데 왜 연락해~ ㅎㅎ 사실 좋지?'},
    ],
    tip: '"미워"는 친밀감의 표현인 경우가 많아요. 진지하게 받지 말고 가볍게 받아줘요.',
  },

  /* ── 17. 관계 불안·확인 ─────────────────────────────── */
  {
    keys: ['우리 괜찮아', '우리 사이 괜찮아', '나한테 뭔가 있어', '우리 좋은 거야'],
    relation: ['lover','some','friend'],
    surface: '관계 상태 확인',
    hidden: '불안함을 느끼고 있음. 안심이 필요한 상태',
    possibilities: [{label:'불안·확인 원함',pct:60},{label:'관계 점검',pct:30},{label:'대화 시도',pct:10}],
    emotions: ['🥺 불안','💗 안심원함'],
    action: '"당연하지, 왜?" 하고 먼저 안심시켜주세요.',
    confidence: 78,
    replies: [
      {style:'공감',text:'당연하지. 왜? 뭔가 불안한 거 있어?'},
      {style:'다정',text:'응, 괜찮아. 뭐가 걱정됐어?'},
      {style:'유머',text:'괜찮냐고? 당연하지 ㅋㅋ 왜 그런 생각 했어?'},
      {style:'썸',text:'당연히 좋은 거야~ 왜 이런 생각 해 ㅎㅎ'},
    ],
    tip: '관계 상태를 확인하는 질문에는 즉시 안심시켜주는 게 중요해요.',
  },
  {
    keys: ['나 어때', '나 괜찮아 보여', '나 요즘 어때 보여', '나 어때 보여'],
    relation: ['lover','some','friend'],
    surface: '자신에 대한 평가 요청',
    hidden: '인정받고 싶음. 상대의 시선이 궁금한 상태',
    possibilities: [{label:'인정·칭찬 원함',pct:55},{label:'외모·상태 확인',pct:30},{label:'관심 확인',pct:15}],
    emotions: ['🥺 인정원함','💗 관심'],
    action: '솔직하면서도 긍정적인 반응을 먼저 보여주세요.',
    confidence: 72,
    replies: [
      {style:'공감',text:'괜찮아 보여. 오히려 요즘 좋아 보이는데?'},
      {style:'다정',text:'좋아 보여 :) 뭔가 좋은 일 있어?'},
      {style:'유머',text:'왜 갑자기? ㅋㅋ 늘 좋아 보이지'},
      {style:'썸',text:'솔직히 요즘 엄청 좋아 보여. 뭔데?'},
    ],
    tip: '상대가 자신에 대한 평가를 물을 때는 진심 어린 칭찬이 효과적이에요.',
  },
  {
    keys: ['날 좋아해', '나 좋아하는 거야', '나한테 관심 있어', '나 어떻게 생각해'],
    relation: ['some','lover'],
    surface: '감정 직접 확인',
    hidden: '고백 직전 단계. 상대의 마음을 먼저 확인하고 싶은 상태',
    possibilities: [{label:'감정 확인',pct:60},{label:'고백 전 탐색',pct:30},{label:'장난',pct:10}],
    emotions: ['💗 설렘','🥺 긴장'],
    action: '솔직하게 현재 마음 상태를 표현해주세요. 애매하게 굴면 안 됩니다.',
    confidence: 85,
    replies: [
      {style:'공감',text:'솔직히 말하면... 좋아하는 것 같아'},
      {style:'다정',text:'왜 이런 걸 물어봐. 티 안 났어? :)'},
      {style:'유머',text:'갑자기 이게 뭔 질문이야 ㅋㅋ 글쎄~'},
      {style:'썸',text:'좋아한다고 하면 어떻게 할 거야? ㅎㅎ'},
    ],
    tip: '이 질문에 애매하게 대답하면 상대가 포기할 수 있어요. 솔직하게 표현하세요.',
  },
  {
    keys: ['나 기억해', '그거 기억나', '내가 말했던 거 기억해', '아직 기억해'],
    relation: ['lover','some','friend'],
    surface: '기억 확인',
    hidden: '자신이 상대에게 중요한 사람인지 확인하고 싶음',
    possibilities: [{label:'소중함 확인',pct:55},{label:'공유한 순간 추억',pct:30},{label:'단순 확인',pct:15}],
    emotions: ['💗 소중함','🥺 인정원함'],
    action: '기억하고 있다면 구체적으로 말해주세요. 기억 못하면 솔직하게.',
    confidence: 74,
    replies: [
      {style:'공감',text:'응 기억해. ○○ 때 말한 거지?'},
      {style:'다정',text:'당연하지. 네가 한 말은 다 기억해'},
      {style:'유머',text:'기억하지 ㅋㅋ 왜? 까먹을까 봐 확인하는 거야?'},
      {style:'썸',text:'기억해. 네가 한 말은 잘 기억하는 편이야 :)'},
    ],
    tip: '기억해준다는 것 자체가 상대를 소중하게 여긴다는 강력한 신호예요.',
  },

  /* ── 18. 기대·설렘 표현 ─────────────────────────────── */
  {
    keys: ['설레', '설렌다', '긴장돼', '떨려'],
    relation: ['lover','some'],
    surface: '설렘·긴장 표현',
    hidden: '상대에 대한 강한 감정. 관계가 중요한 단계에 있음',
    possibilities: [{label:'상대에 대한 설렘',pct:65},{label:'이벤트 기대',pct:25},{label:'감정 공유',pct:10}],
    emotions: ['🥰 설렘','💗 기대'],
    action: '"나도 설레" 하고 공감해주세요. 이 순간을 소중히 여기세요.',
    confidence: 82,
    replies: [
      {style:'공감',text:'나도 설레. 왜 설레?'},
      {style:'다정',text:'귀엽다 :) 나도 사실 긴장돼'},
      {style:'유머',text:'설레는 이유가 혹시 나야? ㅋㅋ'},
      {style:'썸',text:'나도 엄청 설레. 어떡해 ㅎㅎ'},
    ],
    tip: '설레고 긴장된다는 표현은 진심의 표현이에요. 함께 감정을 나눠주세요.',
  },
  {
    keys: ['기대돼', '너무 기대돼', '빨리 보고 싶어', '언제 봐'],
    relation: ['lover','some','friend'],
    surface: '만남에 대한 기대',
    hidden: '빨리 만나고 싶다는 강한 의지. 관계에 긍정적인 신호',
    possibilities: [{label:'만남 기대',pct:70},{label:'관계 확인',pct:20},{label:'설렘 공유',pct:10}],
    emotions: ['🥰 기대','💗 보고싶음'],
    action: '구체적인 날짜를 제안하거나 기대감을 함께 표현해주세요.',
    confidence: 78,
    replies: [
      {style:'공감',text:'나도 기대돼! 이번 주 토요일 어때?'},
      {style:'다정',text:'빨리 봐야지 :) 언제 시간 돼?'},
      {style:'유머',text:'기대된다고? 나 실망시키면 어쩌려고 ㅋㅋ'},
      {style:'썸',text:'나도 빨리 보고 싶어. 이번 주 어때?'},
    ],
    tip: '기대된다는 말 뒤에 바로 날짜를 잡으면 성사율이 2배 높아요.',
  },
  {
    keys: ['꿈에 나왔어', '꿈에 보였어', '어젯밤 꿈에', '꿈에서 봤어'],
    relation: ['lover','some'],
    surface: '꿈 이야기',
    hidden: '자연스럽게 상대를 많이 생각하고 있다는 고백',
    possibilities: [{label:'호감 표현',pct:60},{label:'재미있는 이야기 공유',pct:30},{label:'단순 신기함',pct:10}],
    emotions: ['🥰 설렘','💗 그리움'],
    action: '어떤 꿈이었는지 물어보고 함께 이야기를 나눠보세요.',
    confidence: 74,
    replies: [
      {style:'공감',text:'진짜? 어떤 꿈이었어? 좋은 꿈이었으면 좋겠다'},
      {style:'다정',text:'나도 자주 꿈에 나오면 좋겠다 :)'},
      {style:'유머',text:'꿈에 나왔어? 부동산 수수료 내야 할 것 같은데 ㅋㅋ'},
      {style:'썸',text:'나도 어젯밤에 네 생각 했어. 신기하다 :)'},
    ],
    tip: '꿈에 나왔다는 말은 용기 있는 감정 표현이에요. 가볍게 무시하지 마세요.',
  },

  /* ── 19. 경계·거절 간접 표현 ─────────────────────────────── */
  {
    keys: ['그냥', '그냥 그래', '딱히', '별로 없어'],
    relation: ['lover','some','friend'],
    surface: '특별한 것 없음',
    hidden: '말하기 어려운 게 있거나, 감정이 정리되지 않은 상태',
    possibilities: [{label:'말하기 어려움',pct:45},{label:'진짜 별거 없음',pct:35},{label:'관심 확인',pct:20}],
    emotions: ['😐 망설임','🥺 표현어려움'],
    action: '"그냥이 있네. 뭔지 말해줘도 돼" 하고 부드럽게 열어주세요.',
    confidence: 65,
    replies: [
      {style:'공감',text:'그냥이 있네. 말하기 싫으면 괜찮아'},
      {style:'다정',text:'그냥이 뭐야~ 말해봐. 들을게'},
      {style:'유머',text:'"그냥"은 뭔가 있다는 뜻이잖아 ㅋㅋ 뭔데?'},
      {style:'썸',text:'그냥이 뭔지 궁금한데. 나한테 말해줄 수 있어?'},
    ],
    tip: '"그냥"이라는 말 뒤에는 말 못한 감정이 있는 경우가 많아요.',
  },
  {
    keys: ['아무거나', '뭐든 괜찮아', '네가 정해', '아무 데나'],
    relation: ['lover','some','friend'],
    surface: '결정 위임',
    hidden: '진짜 아무거나가 아닐 수 있음. 상대가 챙겨주길 바라는 것',
    possibilities: [{label:'챙김 원함',pct:50},{label:'진짜 아무거나',pct:35},{label:'삐짐',pct:15}],
    emotions: ['🥺 챙겨주길 원함','😐 무관심 연기'],
    action: '"아무거나" 말고 구체적으로 물어봐서 상대의 취향을 알아내세요.',
    confidence: 68,
    replies: [
      {style:'공감',text:'아무거나 중에 제일 먹고 싶은 거 있어? 한번 골라봐'},
      {style:'다정',text:'그럼 내가 정할게. 한식이랑 일식 중에 뭐야?'},
      {style:'유머',text:'"아무거나"는 뭔가 있다는 뜻 알지? ㅋㅋ 뭐 먹고 싶어?'},
      {style:'썸',text:'아무거나 말고 진짜 먹고 싶은 거 말해봐. 다 들어줄게 :)'},
    ],
    tip: '"아무거나"를 진짜 아무거나로 받으면 나중에 "그건 싫었어"가 나올 수 있어요.',
  },
  {
    keys: ['생각해볼게', '좀 생각해야겠어', '나중에 대답할게', '생각 좀 해보고'],
    relation: ['lover','some','friend'],
    surface: '즉답 회피',
    hidden: '부담스럽거나 확신이 없는 상태. 강요하면 거절이 됨',
    possibilities: [{label:'부담감',pct:45},{label:'진지하게 고민',pct:35},{label:'간접 거절',pct:20}],
    emotions: ['😐 망설임','🥺 부담'],
    action: '"천천히 생각해, 급하지 않아" 하고 공간을 주세요.',
    confidence: 70,
    replies: [
      {style:'공감',text:'천천히 생각해. 급하지 않아 :)'},
      {style:'다정',text:'알겠어. 부담 없이 생각해봐'},
      {style:'유머',text:'생각 오래 하면 답이 나오나? ㅋㅋ 천천히 해'},
      {style:'썸',text:'생각해봐. 그 사이 나 더 잘해줄게 ㅎㅎ'},
    ],
    tip: '생각해보겠다는 말을 재촉하면 거절로 이어지는 경우가 많아요.',
  },
  {
    keys: ['나 혼자 있고 싶어', '혼자 있을게', '좀 쉬고 싶어', '오늘은 좀 쉴게'],
    relation: ['lover','some','friend'],
    surface: '혼자 있고 싶음',
    hidden: '감정이 과부하 상태. 강요하면 더 멀어질 수 있음',
    possibilities: [{label:'충전 시간 필요',pct:55},{label:'감정 정리 필요',pct:35},{label:'거리 두기',pct:10}],
    emotions: ['😔 지침','🧘 혼자시간'],
    action: '"알겠어, 쉬어. 필요하면 연락해"라고 공간을 드리세요.',
    confidence: 75,
    replies: [
      {style:'공감',text:'알겠어. 충분히 쉬어. 필요하면 연락해'},
      {style:'다정',text:'쉬고 싶으면 쉬어. 나 여기 있을게 :)'},
      {style:'유머',text:'혼자 있겠다고? 그럼 나도 혼자 있을게 ㅋㅋ 쉬어~'},
      {style:'썸',text:'응 쉬어. 다음에 좋은 컨디션으로 봐 :)'},
    ],
    tip: '혼자 있고 싶다는 말에 집착하면 관계가 빠르게 나빠져요.',
  },

  /* ── 20. 일상 안부·케어 표현 ─────────────────────────────── */
  {
    keys: ['밥은 먹었어', '밥 먹었어', '점심은', '저녁은 먹었어'],
    relation: ['lover','some','friend','family'],
    surface: '식사 확인',
    hidden: '상대를 챙기고 싶은 마음. 일상적 애정 표현',
    possibilities: [{label:'케어·챙김',pct:60},{label:'대화 시작',pct:30},{label:'단순 안부',pct:10}],
    emotions: ['💗 챙김','😊 따뜻함'],
    action: '"응 먹었어, 너는?" 하고 자연스럽게 안부를 주고받으세요.',
    confidence: 75,
    replies: [
      {style:'공감',text:'응 먹었어 :) 너는?'},
      {style:'다정',text:'방금 먹었어~ 챙겨줘서 고마워'},
      {style:'유머',text:'밥부터 물어봐? 나 다이어트 중인데 ㅋㅋ 응 먹었어'},
      {style:'썸',text:'응 먹었어. 왜? 같이 먹을 거야?'},
    ],
    tip: '밥 먹었냐는 질문은 사랑의 언어예요. 짧게라도 따뜻하게 답해주세요.',
  },
  {
    keys: ['아파', '몸이 안 좋아', '열이 나', '감기 걸렸어', '두통'],
    relation: ['lover','some','friend','family'],
    surface: '아프다고 알림',
    hidden: '걱정해주길 바람. 혼자 있기 싫은 상태',
    possibilities: [{label:'걱정·케어 원함',pct:60},{label:'단순 공유',pct:30},{label:'만남 핑계',pct:10}],
    emotions: ['🥺 힘듦','💗 케어원함'],
    action: '즉시 걱정을 표현하고 도울 방법을 물어보세요.',
    confidence: 80,
    replies: [
      {style:'공감',text:'많이 아파? 병원은 갔어?'},
      {style:'다정',text:'괜찮아? 내가 뭔가 해줄 수 있을까?'},
      {style:'유머',text:'아프다고? 그럼 내가 약 사다줘야 하나? ㅋㅋ 빨리 나아'},
      {style:'썸',text:'아프면 안 되지ㅠ 오늘 봐줄까? 간호해줄게'},
    ],
    tip: '아프다는 말을 가볍게 넘기면 상대가 많이 서운해할 수 있어요.',
  },
  {
    keys: ['졸려', '잠온다', '너무 졸린데', '졸려 죽겠어'],
    relation: ['lover','some','friend'],
    surface: '졸음 표현',
    hidden: '마무리 신호이거나, 아직 대화하고 싶다는 신호일 수 있음',
    possibilities: [{label:'대화 마무리 신호',pct:50},{label:'그래도 더 있고 싶음',pct:35},{label:'단순 졸림 공유',pct:15}],
    emotions: ['😴 졸림','💗 연결유지'],
    action: '자연스럽게 마무리하되 내일을 약속해두세요.',
    confidence: 65,
    replies: [
      {style:'공감',text:'그럼 자~ 편하게 자고 내일 연락해'},
      {style:'다정',text:'잘 자 :) 오늘 얘기해서 좋았어'},
      {style:'유머',text:'졸리면 자야지~ 꿈에 나 불러주기 있기 ㅋㅋ'},
      {style:'썸',text:'그럼 자. 내일 연락 기다릴게 :)'},
    ],
    tip: '졸리다고 할 때 억지로 붙잡으면 상대가 다음에 연락하기 부담스러워해요.',
  },
  {
    keys: ['수고했어', '고생했어', '오늘 수고했다', '많이 힘들었겠다'],
    relation: ['lover','some','friend','work'],
    surface: '노고 인정',
    hidden: '상대를 소중히 여기는 표현. 하루를 함께 마무리하고 싶은 마음',
    possibilities: [{label:'진심 노고 인정',pct:70},{label:'감사 표현',pct:20},{label:'연결 시도',pct:10}],
    emotions: ['💗 소중함','😊 따뜻함'],
    action: '함께 고생했음을 공감하고, 상대의 노력을 구체적으로 인정해주세요.',
    confidence: 78,
    replies: [
      {style:'공감',text:'나도 수고했어. 오늘 힘들었지?'},
      {style:'다정',text:'네가 더 수고했어. 쉬어 :)'},
      {style:'유머',text:'수고했다고? 그럼 나한테 밥 한 번 사줘 ㅋㅋ'},
      {style:'썸',text:'네가 고생하는 거 알아. 정말 수고했어 :)'},
    ],
    tip: '수고했다는 한 마디가 상대의 하루를 가장 따뜻하게 마무리해줘요.',
  },
  {
    keys: ['잘 잤어', '잘 잤어요', '굿모닝', '아침이다', '일어났어'],
    relation: ['lover','some','friend'],
    surface: '기상 인사',
    hidden: '하루의 첫 연락을 상대와 시작하고 싶은 마음. 관계에 만족하고 있음',
    possibilities: [{label:'연결감 유지',pct:55},{label:'기분 좋은 공유',pct:35},{label:'단순 인사',pct:10}],
    emotions: ['😊 따뜻함','💗 연결감'],
    action: '반갑게 받아주고 오늘 하루를 응원해주세요.',
    confidence: 72,
    replies: [
      {style:'공감',text:'굿모닝! 오늘도 좋은 하루 되어라 :)'},
      {style:'다정',text:'일어났어? 오늘 뭐 해? 잘 먹고 다녀'},
      {style:'유머',text:'드디어 일어났네 ㅋㅋ 오늘도 파이팅!'},
      {style:'썸',text:'굿모닝 :) 오늘 하루도 내 생각 해줘'},
    ],
    tip: '아침 첫 연락을 서로 주고받는 관계는 애착이 강한 관계예요.',
  },
  {
    keys: ['조심해', '조심히 가', '조심히 와', '길 조심해'],
    relation: ['lover','some','friend','family'],
    surface: '안전 당부',
    hidden: '상대를 소중히 여기는 마음. 작지만 강한 애정 표현',
    possibilities: [{label:'진심 걱정',pct:65},{label:'습관적 표현',pct:25},{label:'마무리 인사',pct:10}],
    emotions: ['💗 걱정','😊 소중함'],
    action: '"응, 너도" 하고 따뜻하게 받아주세요.',
    confidence: 75,
    replies: [
      {style:'공감',text:'응! 너도 조심해 :)'},
      {style:'다정',text:'응 고마워. 너도 조심히 가'},
      {style:'유머',text:'항상 조심하지 ㅋㅋ 너도 조심해'},
      {style:'썸',text:'챙겨줘서 고마워 :) 너도 조심해'},
    ],
    tip: '조심하라는 말은 작지만 상대를 얼마나 아끼는지 보여주는 말이에요.',
  },
  {
    keys: ['뭐 먹고 싶어', '뭐 먹을까', '뭐 먹어', '밥 뭐 먹어'],
    relation: ['lover','some','friend'],
    surface: '식사 제안 또는 취향 탐색',
    hidden: '함께 먹고 싶거나, 상대를 위해 챙겨주고 싶은 마음',
    possibilities: [{label:'같이 먹고 싶음',pct:50},{label:'챙겨주고 싶음',pct:35},{label:'대화 시작',pct:15}],
    emotions: ['💗 챙김','😊 함께하고싶음'],
    action: '취향을 솔직하게 말하거나, 함께 먹자고 제안해보세요.',
    confidence: 70,
    replies: [
      {style:'공감',text:'나 요즘 파스타 땡기던데~ 같이 먹으러 갈까?'},
      {style:'다정',text:'뭐 시켜줄 거야? :) 된장찌개!'},
      {style:'유머',text:'뭐 먹고 싶냐고? 너 한 번 보는 게 더 먹고 싶다 ㅋㅋ'},
      {style:'썸',text:'뭐든 같이 먹으면 다 맛있어. 같이 먹자 :)'},
    ],
    tip: '함께 먹는 것을 제안하는 건 자연스럽게 만남을 유도하는 방법이에요.',
  },
  {
    keys: ['추워', '오늘 엄청 춥다', '날씨 되게 춥네', '따뜻하게 입어'],
    relation: ['lover','some','friend'],
    surface: '날씨 공유',
    hidden: '상대와 일상을 나누고 싶은 마음. 챙겨주기 원하거나 챙겨주고 싶음',
    possibilities: [{label:'일상 공유',pct:45},{label:'챙겨주길 원함',pct:35},{label:'대화 시작',pct:20}],
    emotions: ['😊 연결감','💗 챙김'],
    action: '날씨에 맞는 걱정이나 공감으로 자연스럽게 대화를 이어가세요.',
    confidence: 65,
    replies: [
      {style:'공감',text:'그렇지? 오늘 진짜 춥더라. 따뜻하게 입고 다녀'},
      {style:'다정',text:'따뜻하게 입었어? 감기 걸리지 마 :)'},
      {style:'유머',text:'추우면 나한테 붙어 있으면 돼 ㅋㅋ 따뜻하게 입어'},
      {style:'썸',text:'추운 날엔 같이 있어야 하는데ㅎ 따뜻하게 다녀:)'},
    ],
    tip: '날씨 이야기로 시작된 대화가 만남 제안으로 이어지는 경우가 많아요.',
  },
  {
    keys: ['사진 찍었어', '셀카 찍었어', '나 잘 나왔어', '사진 봐봐'],
    relation: ['lover','some','friend'],
    surface: '사진 공유',
    hidden: '상대에게 자신을 보여주고 싶음. 반응을 기대하고 있음',
    possibilities: [{label:'반응·관심 원함',pct:60},{label:'일상 공유',pct:30},{label:'추억 만들기',pct:10}],
    emotions: ['💗 관심원함','🥰 설렘'],
    action: '사진에 대한 구체적이고 진심 어린 반응을 보여주세요.',
    confidence: 72,
    replies: [
      {style:'공감',text:'진짜 잘 나왔다! 오늘 기분 좋아 보여'},
      {style:'다정',text:'어머 예뻐/잘생겼어! 나한테도 보내줘 :)'},
      {style:'유머',text:'사진 잘 나왔네 ㅋㅋ 내 저장함 행복해졌어'},
      {style:'썸',text:'진짜 잘 나왔어. 자꾸 보게 되는데 어떡해 :)'},
    ],
    tip: '사진을 보내는 행동 자체가 상대를 신뢰하고 가까워지고 싶다는 신호예요.',
  },
  {
    keys: ['같이 가자', '나도 데려가', '나도 가도 돼', '같이 할래'],
    relation: ['lover','some','friend'],
    surface: '동행 요청',
    hidden: '함께하고 싶은 마음. 상대와 경험을 나누고 싶음',
    possibilities: [{label:'함께 하고 싶음',pct:65},{label:'혼자 가기 싫음',pct:25},{label:'새로운 경험 탐색',pct:10}],
    emotions: ['💗 함께하고싶음','😊 설렘'],
    action: '거절하기 어려운 상황이어도 가능하면 함께하려고 노력해보세요.',
    confidence: 75,
    replies: [
      {style:'공감',text:'같이 가자! 언제야?'},
      {style:'다정',text:'당연하지. 같이 가 :)'},
      {style:'유머',text:'데려가도 되는데, 말 잘 들어야 해 ㅋㅋ 같이 가'},
      {style:'썸',text:'같이 가면 더 좋지~ 날짜 정하자 :)'},
    ],
    tip: '함께 하자는 제안에 거절하면 상대가 많이 실망할 수 있어요.',
  },

  /* ── 21. 고백·감정 전환점 ─────────────────────────────── */
  {
    keys: ['좋아해', '나 너 좋아', '사실 좋아했어', '마음이 생긴 것 같아'],
    relation: ['some','lover'],
    surface: '고백',
    hidden: '큰 용기를 낸 표현. 상대의 반응이 관계의 방향을 결정해요',
    possibilities: [{label:'진심 고백',pct:80},{label:'분위기 탐색',pct:12},{label:'장난',pct:8}],
    emotions: ['🥰 설렘','💗 용기'],
    action: '어떤 감정이든 솔직하게 표현해주세요. 모호한 대답은 상처가 돼요.',
    confidence: 90,
    replies: [
      {style:'공감',text:'나도 사실 마음 생겼어. 같은 마음이야'},
      {style:'다정',text:'고마워. 나도 좋아하는 것 같아 :)'},
      {style:'유머',text:'드디어 말했네 ㅋㅋ 나도야. 진짜로'},
      {style:'썸',text:'그 말 기다렸어. 나도 좋아해 :)'},
    ],
    tip: '고백에는 진심 어린 반응이 필요해요. "생각해볼게"는 상처가 될 수 있어요.',
  },
  {
    keys: ['우리 사귀자', '나랑 사귈래', '사귀어줄래', '내 사람이 돼줘'],
    relation: ['some'],
    surface: '교제 제안',
    hidden: '관계를 공식화하고 싶은 강한 의지. 진지한 감정의 표현',
    possibilities: [{label:'진심 교제 원함',pct:85},{label:'감정 확인',pct:10},{label:'기타',pct:5}],
    emotions: ['💗 진심','🥰 설렘'],
    action: '거절이든 승낙이든 솔직하고 명확하게 답해주세요.',
    confidence: 92,
    replies: [
      {style:'공감',text:'응. 사귀자 :)'},
      {style:'다정',text:'오래 기다렸어. 당연하지 :)'},
      {style:'유머',text:'사귀자고? 그래 해보자 ㅋㅋ'},
      {style:'썸',text:'그 말 듣고 싶었어. 응, 사귀자 :)'},
    ],
    tip: '이 순간의 반응이 평생 기억에 남아요. 진심을 담아 대답해주세요.',
  },
  {
    keys: ['헤어질까봐', '우리 헤어지는 건 아니지', '혹시 나 싫어진 거야'],
    relation: ['lover'],
    surface: '이별 불안 표현',
    hidden: '강한 불안감. 즉각적인 안심이 필요한 상태',
    possibilities: [{label:'심한 불안·확인',pct:65},{label:'관계 위기 감지',pct:25},{label:'관심 확인',pct:10}],
    emotions: ['🥺 불안','💔 두려움'],
    action: '즉시 안심시켜주고, 상대가 왜 그렇게 느끼는지 들어봐야 해요.',
    confidence: 82,
    replies: [
      {style:'공감',text:'무슨 소리야. 절대 아니야. 왜 그런 생각 했어?'},
      {style:'다정',text:'아니야. 내가 뭔가 불안하게 만들었어? 말해줘'},
      {style:'유머',text:'헤어질까봐? 나한테 그런 말 하면 안 되지 ㅋㅋ 절대 아니야'},
      {style:'썸',text:'그런 생각 하지 마. 내가 더 잘할게 :)'},
    ],
    tip: '이런 말이 나왔다면 최근 상대가 불안을 느꼈다는 신호예요. 관계를 점검하세요.',
  },
  {
    keys: ['그냥 보고 싶었어', '이유 없이 연락했어', '그냥 생각나서'],
    relation: ['lover','some','friend'],
    surface: '이유 없이 연락',
    hidden: '용기 내어 먼저 연락한 것. 상대가 보고 싶다는 진심의 표현',
    possibilities: [{label:'보고싶음',pct:65},{label:'관계 확인',pct:25},{label:'단순 연락',pct:10}],
    emotions: ['💗 그리움','😊 설렘'],
    action: '따뜻하게 받아주세요. 먼저 연락한 용기를 소중히 여겨야 해요.',
    confidence: 78,
    replies: [
      {style:'공감',text:'연락해줘서 좋아. 나도 생각하고 있었어'},
      {style:'다정',text:'그냥 연락해줘도 반가워 :)'},
      {style:'유머',text:'이유 없이 생각났다고? 그건 좋아한다는 뜻이잖아 ㅋㅋ'},
      {style:'썸',text:'그냥도 좋아. 자주 연락해 :)'},
    ],
    tip: '이유 없는 연락이 가장 솔직한 감정의 표현이에요.',
  },
  {
    keys: ['너밖에 없어', '너만 믿어', '너한테만 말하는 건데', '다른 사람한테는 못 하는 말'],
    relation: ['lover','some','friend'],
    surface: '특별한 신뢰 표현',
    hidden: '상대를 매우 특별하게 생각함. 깊은 감정적 연결이 있음',
    possibilities: [{label:'깊은 신뢰',pct:70},{label:'공감 요청',pct:20},{label:'외로움',pct:10}],
    emotions: ['💗 신뢰','🥰 특별함'],
    action: '소중하게 받아주고, 비밀을 지킬 것임을 확인해주세요.',
    confidence: 84,
    replies: [
      {style:'공감',text:'나한테 말해줘서 고마워. 절대 비밀 지킬게'},
      {style:'다정',text:'나를 믿어줘서 감동이야. 뭐든 말해봐'},
      {style:'유머',text:'나밖에 없다고? 그 무게 내가 받아줄게 ㅋㅋ 말해봐'},
      {style:'썸',text:'그 말 정말 고마워. 나도 너 특별하게 생각해 :)'},
    ],
    tip: '특별한 신뢰를 표현한 상대에게 가벼운 반응은 금물이에요.',
  },
  {
    keys: ['우리 오늘 만날까', '지금 볼 수 있어', '갑자기 만나자', '오늘 시간 돼'],
    relation: ['lover','some','friend'],
    surface: '즉흥 만남 제안',
    hidden: '지금 당장 보고 싶은 강한 감정. 자발적 만남 추진력',
    possibilities: [{label:'지금 보고싶음',pct:65},{label:'외로움',pct:25},{label:'특별한 계획',pct:10}],
    emotions: ['💗 보고싶음','😊 설렘'],
    action: '가능하다면 적극적으로 응해주세요. 갑작스럽더라도 의미 있는 신호예요.',
    confidence: 78,
    replies: [
      {style:'공감',text:'좋아! 어디서 봐? :)'},
      {style:'다정',text:'가능해. 몇 시에 어디서?'},
      {style:'유머',text:'갑자기? ㅋㅋ 30분 뒤에 가능해. 어디야?'},
      {style:'썸',text:'오 갑자기? 좋아. 어디로 갈까 :)'},
    ],
    tip: '즉흥적인 만남 제안을 거절하면 상대가 위축될 수 있어요. 가능하면 나가세요.',
  },
  {
    keys: ['내 얘기 들어줘', '나 얘기 좀 해도 돼', '할 말이 있는데', '있잖아'],
    relation: ['lover','some','friend'],
    surface: '대화 요청',
    hidden: '중요한 이야기를 꺼내려는 준비 단계. 귀 기울여달라는 신호',
    possibilities: [{label:'진지한 대화 원함',pct:55},{label:'고민 공유',pct:35},{label:'감정 공유',pct:10}],
    emotions: ['🥺 공감원함','💗 신뢰'],
    action: '하던 것을 멈추고 집중해서 들어줄 준비를 하세요.',
    confidence: 76,
    replies: [
      {style:'공감',text:'응 말해봐. 다 들을게'},
      {style:'다정',text:'물론이지. 뭐야? :)'},
      {style:'유머',text:'할 말 있으면 바로 해야지 ㅋㅋ 들을게'},
      {style:'썸',text:'있잖아? 말해봐. 집중해서 들을게 :)'},
    ],
    tip: '"할 말이 있어"는 용기를 낸 표현이에요. 가볍게 받으면 말문이 닫힙니다.',
  },
  {
    keys: ['오늘 뭐 해', '주말에 뭐 해', '이번 주 뭐 해', '오늘 일정 있어'],
    relation: ['lover','some','friend'],
    surface: '일정 확인',
    hidden: '만날 기회를 보고 있음. 직접적인 약속 제안 전 탐색',
    possibilities: [{label:'만남 기회 탐색',pct:55},{label:'단순 안부',pct:30},{label:'함께할 계획',pct:15}],
    emotions: ['💗 보고싶음','😊 기대'],
    action: '일정을 솔직히 말하고, 만남을 자연스럽게 제안해보세요.',
    confidence: 73,
    replies: [
      {style:'공감',text:'별 거 없어. 왜? 뭔 거 있어?'},
      {style:'다정',text:'오후에 시간 있어. 왜? 같이 뭔가 할까?'},
      {style:'유머',text:'왜 물어봐? 부르려고? ㅋㅋ 비어 있어'},
      {style:'썸',text:'딱히 없어~ 혹시 같이 뭔가 하려고? :)'},
    ],
    tip: '일정을 묻는 건 만나자는 말을 꺼내기 전 신호예요. 기회를 열어두세요.',
  },
  {
    keys: ['뭔가 달라진 것 같아', '요즘 왜 이래', '예전이랑 달라', '이상한 것 같아'],
    relation: ['lover','some','friend'],
    surface: '변화 감지',
    hidden: '관계의 변화에 불안감을 느끼고 있음. 솔직한 대화가 필요한 시점',
    possibilities: [{label:'변화에 대한 불안',pct:55},{label:'솔직한 대화 원함',pct:35},{label:'섭섭함 표현',pct:10}],
    emotions: ['🥺 불안','😔 변화감지'],
    action: '변화가 있었다면 솔직히 말해주고, 상대의 불안을 안심시켜주세요.',
    confidence: 76,
    replies: [
      {style:'공감',text:'느꼈구나. 솔직하게 말해줄게. 사실은...'},
      {style:'다정',text:'달라진 게 있어? 말해봐. 같이 풀어가자'},
      {style:'유머',text:'달라진 거 없는데? ㅋㅋ 내가 뭔가 이상했어?'},
      {style:'썸',text:'뭐가 달라 보여? 나는 변한 거 없는데. 뭔가 불안한 거야?'},
    ],
    tip: '이 말이 나왔다면 상대가 많이 힘들었다는 신호예요. 진지하게 받아주세요.',
  }

); // HEARIM_DB.push 끝
})();
