/**
 * 헤아림 - 표현 해석 DB 확장 (38종 추가)
 * data.js 로드 후 HEARIM_DB에 push
 * 총합: 30(core) + 38(extra) = 68종
 */
(function () {

window.HEARIM_DB.push(

  /* ── 6. 긍정·애정 표현 ─────────────────────────────────── */
  {
    keys: ['사랑해', '좋아해', '너 좋아', '너 좋아해', '나 좋아해'],
    relation: ['lover','some'],
    surface: '애정 표현',
    hidden: '용기 있게 마음을 꺼낸 것. 반응이 관계를 결정해요',
    possibilities: [{label:'진심',pct:75},{label:'분위기/장난',pct:15},{label:'시험',pct:10}],
    emotions: ['💗 사랑','🥰 설렘'],
    action: '진지하게 받아주고, 본인의 마음도 솔직하게 표현해보세요.',
    confidence: 90,
    replies: [
      {style:'공감',text:'나도ㅠ 그 말 들으니까 너무 좋다'},
      {style:'다정',text:'나도 좋아해. 그 말 해줘서 고마워 :)'},
      {style:'유머',text:'드디어 고백이야? ㅋㅋ 나도 좋아 진짜'},
      {style:'썸',text:'나도 그 말 기다렸어. 나도 좋아해 :)'},
    ],
    tip: '이 말에 어떻게 반응하느냐가 관계의 다음 단계를 결정해요.',
  },
  {
    keys: ['재밌었어', '즐거웠어', '좋았어', '오늘 좋았어', '오늘 재밌었어'],
    relation: ['lover','some','friend'],
    surface: '긍정적 경험 공유',
    hidden: '함께한 시간이 좋았다는 표현. 또 보고 싶다는 뜻',
    possibilities: [{label:'또 만나고 싶음',pct:60},{label:'단순 감상 공유',pct:30},{label:'관심 유지 시도',pct:10}],
    emotions: ['😊 행복','💗 또 만나고싶음'],
    action: '함께한 것에 동의하고 다음 만남을 자연스럽게 제안하기.',
    confidence: 82,
    replies: [
      {style:'공감',text:'나도! 오늘 진짜 좋았어. 또 하자 :)'},
      {style:'다정',text:'같이여서 더 좋았어. 다음에도 같이 가자'},
      {style:'유머',text:'오늘 내가 재밌게 해준 거잖아 ㅋㅋ 다음에도 불러줘'},
      {style:'썸',text:'나도 오늘 진짜 좋았어. 우리 자주 보자 :)'},
    ],
    tip: '즐거웠다는 표현 뒤에는 다음 약속 제안이 자연스러워요.',
  },
  {
    keys: ['고마워', '감사해', '고마워요', '진짜 고마워', '고마워서'],
    relation: ['lover','some','friend','family','work'],
    surface: '감사 표현',
    hidden: '상대를 소중하게 여기는 마음, 연결감 강화 시도',
    possibilities: [{label:'진심 감사',pct:70},{label:'호감 표현',pct:20},{label:'사교적 표현',pct:10}],
    emotions: ['💗 소중함','😊 따뜻함'],
    action: '"나도 고마워" 하고 따뜻하게 받아주세요.',
    confidence: 80,
    replies: [
      {style:'공감',text:'나도 고마워. 도움이 됐으면 좋겠어'},
      {style:'다정',text:'별말을~ 언제든지 :)'},
      {style:'유머',text:'고맙긴 ㅎㅎ 나한테 고마우면 밥 한 번 사줘'},
      {style:'썸',text:'고맙다고 하니까 더 좋다. 나도 네 덕분에 좋았어 :)'},
    ],
    tip: '"별거 아니야"보다 "나도 고마워"가 관계를 더 따뜻하게 해요.',
  },
  {
    keys: ['요즘 자꾸 생각나', '자꾸 생각나', '자꾸 생각난다', '생각이 자꾸 나'],
    relation: ['lover','some'],
    surface: '자꾸 떠오름',
    hidden: '감정이 깊어진 상태. 고백에 가까운 표현',
    possibilities: [{label:'호감 깊어짐',pct:65},{label:'보고 싶음',pct:25},{label:'설렘 표현',pct:10}],
    emotions: ['💗 설렘','🥰 호감'],
    action: '긍정적으로 받아주고, 본인도 솔직하게 표현해보세요.',
    confidence: 85,
    replies: [
      {style:'공감',text:'나도 요즘 네 생각 자주 해ㅎㅎ'},
      {style:'다정',text:'그 말 들으니까 기분 너무 좋다 :)'},
      {style:'유머',text:'생각나게 한 내가 잘못이네 ㅋㅋ 미안'},
      {style:'썸',text:'나도 자꾸 생각났는데 ㅎㅎ 우리 만날까?'},
    ],
    tip: '"자꾸 생각난다"는 말은 대부분 진심이에요.',
  },

  /* ── 7. 불안·확인 요청 ─────────────────────────────────── */
  {
    keys: ['나 좋아해', '나 어떻게 생각해', '나 어때', '나 좋아하긴 해?'],
    relation: ['lover','some'],
    surface: '감정 확인 요청',
    hidden: '불안하거나 관계를 확신하고 싶은 상태',
    possibilities: [{label:'감정 확인 불안',pct:55},{label:'관계 정리 원함',pct:25},{label:'고백 전 떠보기',pct:20}],
    emotions: ['😟 불안','🥺 확인원함'],
    action: '솔직하고 명확하게 본인 감정을 표현해주세요.',
    confidence: 82,
    replies: [
      {style:'공감',text:'당연하지. 왜 그런 걱정해? 내가 더 잘 표현할게'},
      {style:'다정',text:'좋아해. 근데 왜 갑자기 그런 생각했어?'},
      {style:'유머',text:'이런 질문 하면 더 좋아하게 되는 거 알아? ㅎㅎ'},
      {style:'썸',text:'솔직히? 많이 좋아해. 근데 너는?'},
    ],
    tip: '이런 질문에 회피하면 불안이 더 커져요. 명확하게 표현해주세요.',
  },
  {
    keys: ['우리 잘 되는 거야', '우리 괜찮은 거지', '우리 잘 되고 있는 거지', '우리 사이 괜찮아'],
    relation: ['lover','some'],
    surface: '관계 상태 확인',
    hidden: '불안함. 관계가 흔들리는 것 같은 느낌',
    possibilities: [{label:'관계 불안',pct:60},{label:'확신 원함',pct:30},{label:'변화 감지',pct:10}],
    emotions: ['😟 불안','🥺 확신원함'],
    action: '안심시켜주고 불안의 원인을 부드럽게 물어보세요.',
    confidence: 80,
    replies: [
      {style:'공감',text:'당연하지. 걱정돼? 무슨 일 있었어?'},
      {style:'다정',text:'잘 되고 있어. 내가 더 잘 표현할게ㅠ'},
      {style:'유머',text:'잘 되고 있지! 이렇게 걱정하는 것 자체가 잘 되고 있다는 증거 ㅎㅎ'},
      {style:'썸',text:'응 잘 되고 있어. 불안했으면 미안해. 얘기 더 해'},
    ],
    tip: '이 질문이 나왔다면 최근에 불안감을 줄 일이 있었는지 돌아보세요.',
  },
  {
    keys: ['솔직하게 말해줘', '솔직히 말해', '진짜 어떻게 생각해', '솔직하게'],
    relation: ['lover','some','friend'],
    surface: '솔직한 표현 요구',
    hidden: '숨긴 것이 있다고 느끼거나, 불확실한 것을 명확히 하고 싶음',
    possibilities: [{label:'불안·의심',pct:45},{label:'결단 원함',pct:35},{label:'진심 확인',pct:20}],
    emotions: ['🤔 의심','😟 불안'],
    action: '돌려 말하지 말고 솔직하게 본인 감정을 표현해주세요.',
    confidence: 77,
    replies: [
      {style:'공감',text:'그래, 솔직하게 말할게. 사실은...'},
      {style:'다정',text:'솔직히 말하면 나 너한테 많이 신경 써. 그게 다야'},
      {style:'유머',text:'솔직히? 나 지금 네 생각 중 ㅋㅋ'},
      {style:'썸',text:'솔직히 말하면... 많이 좋아해. 이제 됐어? :)'},
    ],
    tip: '솔직하게 말해달라는 요청에는 솔직함으로 답하는 게 최선이에요.',
  },
  {
    keys: ['왜 갑자기', '갑자기 왜', '갑자기 무슨', '갑자기 연락은'],
    relation: ['lover','some','friend'],
    surface: '갑작스러운 상황에 의문',
    hidden: '예상 못 한 연락이나 행동에 놀람, 또는 살짝 경계',
    possibilities: [{label:'단순 놀람',pct:40},{label:'경계·의심',pct:35},{label:'반가움 숨기는 중',pct:25}],
    emotions: ['😮 놀람','🤔 의아함'],
    action: '이유를 솔직하게 설명하고 부담 없이 접근해보세요.',
    confidence: 65,
    replies: [
      {style:'공감',text:'갑자기 미안ㅎㅎ 그냥 생각나서'},
      {style:'다정',text:'이유가 있어야 연락하면 안 돼? ㅎㅎ'},
      {style:'유머',text:'갑자기가 어딨어. 원래 이럴 것 같은 사람이잖아 나'},
      {style:'썸',text:'보고 싶어서. 갑자기 연락하면 안 돼? :)'},
    ],
    tip: '갑자기 연락했다는 데 놀라는 건 반가워서일 수도 있어요.',
  },

  /* ── 8. 갈등·실망 표현 ─────────────────────────────────── */
  {
    keys: ['실망했어', '실망이야', '좀 실망이다', '솔직히 실망했어'],
    relation: ['lover','some','friend'],
    surface: '실망감 표현',
    hidden: '기대가 있었기 때문에 생긴 감정. 관계를 포기하지 않은 상태',
    possibilities: [{label:'기대 배신',pct:55},{label:'갈등 표출',pct:30},{label:'변화 요구',pct:15}],
    emotions: ['💔 실망','😔 서운함'],
    action: '"내가 기대에 못 미쳤구나. 미안해. 어떻게 하면 좋을까?" 로 접근.',
    confidence: 80,
    replies: [
      {style:'공감',text:'미안해ㅠ 내가 기대에 못 미쳤구나. 어떻게 하면 돼?'},
      {style:'다정',text:'실망했다고 말해줘서 고마워. 다음엔 꼭 다르게 할게'},
      {style:'유머',text:'실망시켜서 미안해... 만회할 기회 줄 거지? ㅎㅎ'},
      {style:'썸',text:'미안해. 다시 잘하고 싶어. 기회 한 번만 더 줄 수 있어?'},
    ],
    tip: '"실망했다"는 말은 아직 기대가 남아있다는 뜻이에요.',
  },
  {
    keys: ['기대했는데', '기대하고 있었는데', '기대했어', '그럴 줄 알았어', '역시 그럼 그렇지'],
    relation: ['lover','some','friend'],
    surface: '기대에 어긋남',
    hidden: '기대를 했었고 배신감을 느끼는 상태',
    possibilities: [{label:'실망',pct:55},{label:'패턴에 지침',pct:30},{label:'포기 직전',pct:15}],
    emotions: ['💔 배신감','😔 실망'],
    action: '"기대하게 해서 미안해. 앞으로는 확실히 할게"로 구체 약속.',
    confidence: 76,
    replies: [
      {style:'공감',text:'기대하게 해서 미안해ㅠ 다음엔 확실히 할게'},
      {style:'다정',text:'내가 실망시킨 거 알아. 정말 미안해'},
      {style:'유머',text:'기대를 저버리다니... 반성한다 ㅠ 만회할게'},
      {style:'썸',text:'미안해. 다음엔 꼭 기대를 채워줄게. 믿어줘 :)'},
    ],
    tip: '"그럼 그렇지"는 반복된 실망의 신호. 행동으로 보여주세요.',
  },
  {
    keys: ['네가 힘들게 해', '너 때문에 힘들어', '너 때문에', '나 너 때문에 많이 힘들었어'],
    relation: ['lover','some','friend'],
    surface: '상대로 인한 고통 표현',
    hidden: '그만큼 중요한 사람이라는 반증. 관계 개선 요구',
    possibilities: [{label:'변화 요구',pct:50},{label:'감정 폭발',pct:30},{label:'관계 재정립 요청',pct:20}],
    emotions: ['😤 분노','💔 상처'],
    action: '먼저 사과하고, 무엇이 힘들었는지 구체적으로 물어보세요.',
    confidence: 78,
    replies: [
      {style:'공감',text:'미안해ㅠ 내가 뭘 잘못했는지 말해줄 수 있어?'},
      {style:'다정',text:'그렇게 힘들게 했는지 몰랐어. 진짜 미안해'},
      {style:'유머',text:'ㅠ 나 반성하고 있어. 풀어줄 거지?'},
      {style:'썸',text:'미안해. 다시는 그러지 않을게. 만나서 얘기하자'},
    ],
    tip: '"그러니까 네가 왜"로 반박하면 관계가 더 나빠져요.',
  },
  {
    keys: ['우리 좀 쉬자', '잠깐 쉬어가자', '좀 쉬고 싶어', '우리 거리를 두자'],
    relation: ['lover','some'],
    surface: '관계에서 거리 요청',
    hidden: '소진 상태이거나 갈등이 해소되지 않아 공간이 필요함',
    possibilities: [{label:'에너지 소진',pct:35},{label:'감정 정리 필요',pct:40},{label:'이별 전 단계',pct:25}],
    emotions: ['😔 소진','🔋 방전'],
    action: '압박하지 말고 "알겠어, 네 생각 존중해. 나중에 얘기하자"로 대응.',
    confidence: 72,
    replies: [
      {style:'공감',text:'알겠어. 네 생각 존중해. 편할 때 연락해'},
      {style:'다정',text:'쉬는 건 좋아. 그래도 완전히 놓치고 싶진 않아'},
      {style:'유머',text:'쉰다고? 나는 어쩌라고 ㅠ 그래도 완전히 없어지진 마'},
      {style:'썸',text:'알겠어. 쉬어. 근데 완전히 사라지진 말아줘'},
    ],
    tip: '이 말이 나왔다면 매달리기보다 여유를 주는 게 현명해요.',
  },
  {
    keys: ['그냥 친구로 지내자', '우리 그냥 친구 하자', '친구로만 지내자', '그냥 친구가 좋을 것 같아'],
    relation: ['some','lover'],
    surface: '연인 관계 제안 거절 또는 관계 하향',
    hidden: '거절이지만 관계 자체는 유지하고 싶은 마음',
    possibilities: [{label:'연인 관계 거절',pct:60},{label:'관계 정리',pct:25},{label:'아직 확신 없음',pct:15}],
    emotions: ['😔 거절','🤝 우정 유지'],
    action: '감정 정리가 필요해요. 억지로 이어가기보다 자신을 먼저 돌봐주세요.',
    confidence: 85,
    replies: [
      {style:'공감',text:'알겠어. 솔직하게 말해줘서 고마워'},
      {style:'다정',text:'그래, 네 선택 존중해. 그래도 좋은 사이 이어갔으면 좋겠어'},
      {style:'유머',text:'친구도 나쁘지 않지 뭐 ㅎㅎ... 라고 해야겠지'},
      {style:'썸',text:'알겠어. 근데 마음이 바뀌면 꼭 말해줘 :)'},
    ],
    tip: '친구로 지내자는 말을 번복시키려 할수록 역효과가 나요.',
  },

  /* ── 9. 자기개방·고민 공유 ──────────────────────────────── */
  {
    keys: ['나 고민이 있어', '고민이 있는데', '나 고민이야', '고민이 하나 있는데'],
    relation: ['lover','some','friend'],
    surface: '고민 공유 시작',
    hidden: '신뢰하기 때문에 꺼내는 말. 공감을 원함',
    possibilities: [{label:'조언 원함',pct:35},{label:'공감·위로 원함',pct:55},{label:'말하고 싶어서',pct:10}],
    emotions: ['🥺 신뢰','🤔 고민'],
    action: '"말해줘, 들을게" 하고 먼저 조언하지 말고 끝까지 들으세요.',
    confidence: 82,
    replies: [
      {style:'공감',text:'말해줘. 어떤 고민인데?'},
      {style:'다정',text:'들을게. 편하게 얘기해 :)'},
      {style:'유머',text:'고민? 내가 해결해줄게 ㅎㅎ 뭔데'},
      {style:'썸',text:'말해봐. 같이 생각해볼게 :)'},
    ],
    tip: '고민을 나누는 건 신뢰의 표시예요. 조언보다 공감이 먼저예요.',
  },
  {
    keys: ['나 요즘 이상한 것 같아', '나 좀 이상하지', '나 요즘 좀 이상해'],
    relation: ['lover','some','friend'],
    surface: '자기 변화 인식·공유',
    hidden: '불안하거나 감정 기복이 있는 상태. 받아줬으면 함',
    possibilities: [{label:'위로 원함',pct:50},{label:'공감 원함',pct:35},{label:'변화 자각',pct:15}],
    emotions: ['😟 불안','🥺 위로필요'],
    action: '"이상한 거 없어. 요즘 힘든 거 있어?" 하고 안심시켜주세요.',
    confidence: 73,
    replies: [
      {style:'공감',text:'이상하지 않아. 요즘 뭔가 힘든 거 있어?'},
      {style:'다정',text:'그럴 수 있어. 말해주면 같이 생각해볼게'},
      {style:'유머',text:'원래 이상했잖아 ㅋㅋ 농담이고, 무슨 일 있어?'},
      {style:'썸',text:'이상한 게 아니야. 나한테 말해줘 :)'},
    ],
    tip: '"왜 이상해?"보다 "힘든 거 있어?"가 더 공감이 돼요.',
  },
  {
    keys: ['솔직히 말하면', '솔직히', '사실은', '사실은 말이야', '솔직히 얘기하자면'],
    relation: ['lover','some','friend'],
    surface: '솔직한 표현 시작',
    hidden: '용기 내서 진심을 꺼내려는 중. 잘 받아줘야 해요',
    possibilities: [{label:'진심 표현',pct:55},{label:'불만 표출',pct:30},{label:'갈등 해소 시도',pct:15}],
    emotions: ['💪 용기','😶 고백'],
    action: '끊지 말고 끝까지 듣고 나서 반응해주세요.',
    confidence: 78,
    replies: [
      {style:'공감',text:'응, 말해봐. 다 들을게'},
      {style:'다정',text:'솔직하게 말해줘서 고마워. 다 들을 준비 됐어'},
      {style:'유머',text:'솔직한 거 좋아! 뭔데 ㅎㅎ'},
      {style:'썸',text:'말해봐. 뭔 말이든 괜찮아 :)'},
    ],
    tip: '솔직하게 말한다는 것 자체가 신뢰와 용기의 표현이에요.',
  },
  {
    keys: ['있잖아', '저기', '있잖아요', '저기 있잖아', '그게 있잖아'],
    relation: ['lover','some','friend'],
    surface: '말 꺼내기 전 뜸들이기',
    hidden: '하고 싶은 말이 있지만 어떻게 꺼낼지 고민 중',
    possibilities: [{label:'중요한 말이 있음',pct:50},{label:'분위기 탐색',pct:30},{label:'단순 대화 시작',pct:20}],
    emotions: ['🥺 망설임','💗 하고싶은말'],
    action: '"응 말해봐" 하고 여유 있게 기다려주세요.',
    confidence: 65,
    replies: [
      {style:'공감',text:'응? 뭔데 ㅎㅎ 말해봐'},
      {style:'다정',text:'있잖아? 응 말해 :)'},
      {style:'유머',text:'"있잖아"로 시작하는 말이 늘 뭔가 있더라 ㅎㅎ'},
      {style:'썸',text:'있잖아 뭐? 말해봐, 다 들을게 :)'},
    ],
    tip: '있잖아 다음엔 들을 준비를 하세요. 중요한 말이 올 수 있어요.',
  },

  /* ── 10. 연락 패턴·변화 ────────────────────────────────── */
  {
    keys: ['연락이 없네', '연락 좀 해', '왜 연락이 없어', '연락 안 하네'],
    relation: ['lover','some','friend'],
    surface: '연락 부재에 대한 불만',
    hidden: '걱정하거나 보고 싶다는 표현. 관계에 관심이 있다는 신호',
    possibilities: [{label:'보고싶음',pct:45},{label:'서운함',pct:40},{label:'변화 감지',pct:15}],
    emotions: ['🥺 보고싶음','😔 서운함'],
    action: '사과 후 이유를 설명하고 앞으로 자주 연락하겠다고 말해주세요.',
    confidence: 78,
    replies: [
      {style:'공감',text:'미안해ㅠ 바쁘다는 핑계로 연락을 못 했어'},
      {style:'다정',text:'보고 싶었어? ㅎㅎ 나도 연락 더 자주 할게'},
      {style:'유머',text:'연락 안 한 게 생각났구나? 나 그리웠지? ㅎㅎ'},
      {style:'썸',text:'미안해. 앞으로 더 자주 연락할게. 오늘 한 번 볼래?'},
    ],
    tip: '연락이 없다고 표현하는 건 관계를 포기하지 않았다는 신호예요.',
  },
  {
    keys: ['뭔가 이상해', '뭔가 달라진 것 같아', '뭔가 어색해', '분위기가 이상한데'],
    relation: ['lover','some','friend'],
    surface: '관계 변화 감지',
    hidden: '불안하게 만드는 변화를 느끼고 있음. 확인 원함',
    possibilities: [{label:'실제 변화 감지',pct:50},{label:'불안 과잉',pct:30},{label:'갈등 전조',pct:20}],
    emotions: ['😟 불안','🤔 감지'],
    action: '"뭔가 느껴지는 거 있어? 솔직히 말해줘" 하고 열어주세요.',
    confidence: 70,
    replies: [
      {style:'공감',text:'뭔가 이상하게 느꼈어? 솔직히 말해줘. 들을게'},
      {style:'다정',text:'내가 이상하게 행동했어? 알려줘, 고치고 싶어'},
      {style:'유머',text:'이상한 거야 아니야 ㅋㅋ 뭔데 말해봐'},
      {style:'썸',text:'느낌이 왔구나? 뭔지 말해줘. 같이 얘기하자'},
    ],
    tip: '이상하다고 느끼는 건 예민한 게 아니에요. 솔직히 물어보는 게 좋아요.',
  },
  {
    keys: ['연락하기 무서워졌어', '연락하기가 무서워', '연락이 두려워', '연락할까 말까'],
    relation: ['lover','some','friend'],
    surface: '연락 망설임',
    hidden: '상처를 받았거나, 거절이 두려운 상태',
    possibilities: [{label:'상처/거절 경험',pct:50},{label:'관계 눈치 보임',pct:35},{label:'자존감 위축',pct:15}],
    emotions: ['😟 두려움','🥺 상처'],
    action: '"연락해줘서 좋아. 항상 괜찮으니까 연락해" 하고 문을 열어주세요.',
    confidence: 75,
    replies: [
      {style:'공감',text:'무섭게 한 거 있었어? 미안해. 언제든 연락해'},
      {style:'다정',text:'연락해줘서 좋아. 앞으로도 부담 없이 연락해 :)'},
      {style:'유머',text:'뭐가 무서워? 나잖아 ㅎㅎ 언제든 연락해도 돼'},
      {style:'썸',text:'연락해줘서 좋아. 무섭지 않아도 돼 :)'},
    ],
    tip: '연락을 두려워한다면 과거에 상처가 있었던 거예요. 먼저 다가가주세요.',
  },
  {
    keys: ['우리 사이가 어색해진 것 같아', '요즘 좀 어색하지 않아', '우리 어색해'],
    relation: ['lover','some','friend'],
    surface: '어색함 인지',
    hidden: '관계가 변했다고 느끼며 회복을 원함',
    possibilities: [{label:'회복 원함',pct:50},{label:'확인 원함',pct:30},{label:'갈등 후 상태',pct:20}],
    emotions: ['😶 어색함','🥺 회복원함'],
    action: '"나도 느꼈어. 우리 예전처럼 편하게 대화해보자" 로 먼저 제안하기.',
    confidence: 73,
    replies: [
      {style:'공감',text:'나도 좀 그랬어. 우리 좀 더 편하게 얘기하자'},
      {style:'다정',text:'어색해진 것 같아서 먼저 말해줘서 고마워. 풀자 :)'},
      {style:'유머',text:'어색하긴 뭐가~ 원래 좀 이랬잖아 ㅋㅋ 풀자'},
      {style:'썸',text:'어색했어? 내가 더 편하게 대해줄게 :)'},
    ],
    tip: '어색함을 먼저 꺼내는 건 관계를 회복하고 싶다는 신호예요.',
  },

  /* ── 11. 승인·보류·마무리 표현 ────────────────────────── */
  {
    keys: ['노력할게', '노력해볼게', '노력해볼게요', '해볼게'],
    relation: ['lover','some','friend','work'],
    surface: '개선 의지 표현',
    hidden: '아직 확신은 없지만 시도는 해보겠다는 의미',
    possibilities: [{label:'진심 의지',pct:45},{label:'갈등 봉합용',pct:35},{label:'기대에 부응 시도',pct:20}],
    emotions: ['💪 의지','😔 부담'],
    action: '고마움을 표현하고 구체적인 방향을 같이 정해주세요.',
    confidence: 65,
    replies: [
      {style:'공감',text:'고마워. 어떻게 하면 좋을지 같이 생각해보자'},
      {style:'다정',text:'노력해준다니 정말 고마워. 나도 잘 할게'},
      {style:'유머',text:'오! 노력하겠다고? 믿어볼게 ㅎㅎ'},
      {style:'썸',text:'노력해줘서 고마워. 나도 같이 잘 해볼게 :)'},
    ],
    tip: '"노력할게"는 좋은 신호지만 행동으로 이어져야 의미 있어요.',
  },
  {
    keys: ['생각해볼게', '생각해볼게요', '좀 생각해봐야겠어', '생각해봐야 할 것 같아'],
    relation: ['lover','some','friend','work'],
    surface: '결정 보류',
    hidden: '바로 OK하기 어렵거나, 더 고려가 필요한 상황',
    possibilities: [{label:'진심 고민',pct:40},{label:'완곡한 거절',pct:35},{label:'시간 필요',pct:25}],
    emotions: ['🤔 고민','⏱ 보류'],
    action: '결과를 기다리되 "편한 때 알려줘" 하고 여유를 주세요.',
    confidence: 60,
    replies: [
      {style:'공감',text:'알겠어. 천천히 생각해봐'},
      {style:'다정',text:'부담 없이 생각해봐. 편할 때 말해줘 :)'},
      {style:'유머',text:'생각하다가 잊지는 말고 ㅎㅎ 기다릴게'},
      {style:'썸',text:'천천히 생각해봐. 나 기다릴 수 있어 :)'},
    ],
    tip: '"생각해볼게"가 계속 이어지면 원하는 게 뭔지 직접 물어보세요.',
  },
  {
    keys: ['잠깐만', '잠깐 기다려', '조금만 기다려', '잠깐'],
    relation: ['lover','some','friend','work'],
    surface: '시간 요청',
    hidden: '지금 여건이 안 되거나, 감정 정리가 필요한 상태',
    possibilities: [{label:'실제 바쁨',pct:50},{label:'감정 정리 중',pct:30},{label:'대화 부담',pct:20}],
    emotions: ['⏱ 시간필요','🔋 정리중'],
    action: '"천천히 해, 기다릴게" 하고 압박 없이 기다려주세요.',
    confidence: 62,
    replies: [
      {style:'공감',text:'응 기다릴게 :)'},
      {style:'다정',text:'천천히 해. 나 여기 있어'},
      {style:'유머',text:'잠깐이 얼마나 길지 모르지만 기다릴게 ㅎㅎ'},
      {style:'썸',text:'기다릴게. 준비되면 말해줘 :)'},
    ],
    tip: '재촉하면 더 오래 기다리게 돼요. 여유 있는 태도가 효과적이에요.',
  },
  {
    keys: ['일어났어', '일어났어?', '벌써 일어났어', '자고 일어났어'],
    relation: ['lover','some','friend'],
    surface: '기상 확인',
    hidden: '아침부터 생각났다는 관심 표현',
    possibilities: [{label:'아침부터 생각남',pct:60},{label:'만날 계획 시작',pct:25},{label:'단순 안부',pct:15}],
    emotions: ['💗 관심','😊 챙김'],
    action: '따뜻하게 받고 오늘 하루 일정을 가볍게 이어가보세요.',
    confidence: 74,
    replies: [
      {style:'공감',text:'응 방금 일어났어! 너는?'},
      {style:'다정',text:'일어났어~ 아침부터 생각해줘서 좋다 :)'},
      {style:'유머',text:'일어났지! 아침부터 내 생각 한 거야? ㅎㅎ'},
      {style:'썸',text:'지금 막 일어났어. 오늘 뭐 해? :)'},
    ],
    tip: '아침 첫 메시지를 보냈다는 건 자기 전에도 생각했다는 신호예요.',
  },
  {
    keys: ['오늘 좋았어', '오늘 좀 특별했어', '오늘 즐거웠어', '오늘 행복했어'],
    relation: ['lover','some','friend'],
    surface: '오늘 긍정적 경험 공유',
    hidden: '상대 덕분에 좋았다는 뜻이거나, 좋은 감정을 나누고 싶음',
    possibilities: [{label:'상대 덕분',pct:50},{label:'감정 공유 원함',pct:35},{label:'단순 공유',pct:15}],
    emotions: ['😊 행복','💗 공유'],
    action: '"나도 좋았어. 덕분이야 :)" 하고 같이 기분을 나눠주세요.',
    confidence: 78,
    replies: [
      {style:'공감',text:'나도 오늘 좋았어. 같이여서 더 그랬어'},
      {style:'다정',text:'그 말 들으니까 나도 기분 좋아 :)'},
      {style:'유머',text:'내가 있어서 좋았던 거잖아? ㅋㅋ 인정해'},
      {style:'썸',text:'나도 오늘 진짜 좋았어. 또 이런 날 만들자 :)'},
    ],
    tip: '좋은 감정을 공유할 때는 함께 즐겨주는 반응이 가장 효과적이에요.',
  },

  /* ── 12. 직장·가족 특화 ────────────────────────────────── */
  {
    keys: ['알겠습니다', '알겠어요', '확인했습니다', '네 알겠어요'],
    relation: ['work','family'],
    surface: '확인/동의',
    hidden: '동의는 했지만 부담이 있을 수 있음',
    possibilities: [{label:'진심 동의',pct:55},{label:'어쩔 수 없는 수락',pct:30},{label:'형식적 답변',pct:15}],
    emotions: ['😐 수락','🤔 부담'],
    action: '부담이 없는지 한 번 더 확인해주면 신뢰가 생겨요.',
    confidence: 60,
    replies: [
      {style:'공감',text:'감사합니다. 진행하면서 궁금한 점 있으면 편하게 말해주세요'},
      {style:'다정',text:'알겠어요! 도움 필요하면 말해'},
      {style:'유머',text:'알겠다고? 믿어볼게 ㅎㅎ'},
      {style:'썸',text:'알겠어 :) 잘 부탁해'},
    ],
    tip: '직장에서 "알겠습니다"는 이행이 있어야 의미가 있어요.',
  },
  {
    keys: ['걱정 마', '걱정하지 마', '걱정 안 해도 돼', '괜찮으니까 걱정 마'],
    relation: ['family','friend','lover'],
    surface: '걱정 불필요',
    hidden: '혼자 해결하려 하거나, 걱정을 부담스러워함',
    possibilities: [{label:'진짜 괜찮음',pct:40},{label:'혼자 처리 원함',pct:40},{label:'표현 못 함',pct:20}],
    emotions: ['💪 독립','😶 숨김'],
    action: '"알겠어, 그래도 뭔가 필요하면 말해줘" 하고 문은 열어두기.',
    confidence: 68,
    replies: [
      {style:'공감',text:'알겠어. 그래도 필요하면 말해 :)'},
      {style:'다정',text:'걱정은 하지 않을게. 대신 힘들면 꼭 말해줘'},
      {style:'유머',text:'걱정하지 마라고? 이미 걱정했는데 ㅎㅎ 그래도 알겠어'},
      {style:'썸',text:'알겠어. 근데 나 챙겨줄게. 거절 못 해 :)'},
    ],
    tip: '걱정 마라는 말에도 "있으면 말해줘"를 남겨두세요.',
  },

  /* ── 13. 특수·복합 상황 ────────────────────────────────── */
  {
    keys: ['진짜', '정말', '헐', '대박', '진짜?', '정말?'],
    relation: ['lover','some','friend'],
    surface: '놀람/강조',
    hidden: '감정 반응이 크거나 대화를 이어가고 싶음',
    possibilities: [{label:'진심 놀람',pct:50},{label:'공감/동조',pct:35},{label:'대화 유지 시도',pct:15}],
    emotions: ['😮 놀람','💗 흥미'],
    action: '반응을 보이고 더 자세히 물어보며 대화를 이어가세요.',
    confidence: 60,
    replies: [
      {style:'공감',text:'진짜야! 더 얘기해줄까? ㅎㅎ'},
      {style:'다정',text:'응 진짜야. 신기하지 :)'},
      {style:'유머',text:'진짜라고~ 믿어봐! ㅋㅋ'},
      {style:'썸',text:'진짜야. 더 알고 싶어? :)'},
    ],
    tip: '"진짜?"로 반응하는 상대는 대화에 흥미를 느끼고 있어요.',
  },
  {
    keys: ['같이 갈래', '같이 가자', '같이 가볼래', '나랑 같이 가자', '같이 가줄래'],
    relation: ['lover','some','friend'],
    surface: '동행 제안',
    hidden: '함께하고 싶고, 상대와 시간을 보내고 싶음',
    possibilities: [{label:'진심 동행 원함',pct:65},{label:'관계 발전 시도',pct:25},{label:'단순 편의',pct:10}],
    emotions: ['💗 함께하고싶음','🥰 기대'],
    action: '긍정적으로 받아들이고 일정을 구체화해보세요.',
    confidence: 80,
    replies: [
      {style:'공감',text:'좋아! 언제 어디 가는 건데?'},
      {style:'다정',text:'같이 가고 싶어! 언제로 생각해? :)'},
      {style:'유머',text:'나 없으면 못 가나 ㅋㅋ 좋아 같이 가자'},
      {style:'썸',text:'같이 가자! 더 기대되는데 :)'},
    ],
    tip: '같이 가자는 말은 상대와의 시간이 소중하다는 신호예요.',
  },
  {
    keys: ['밥 한번 먹자', '밥 먹을래', '밥 같이 먹자', '밥 한 끼 하자', '같이 밥 먹자'],
    relation: ['lover','some','friend','work'],
    surface: '식사 제안',
    hidden: '만남의 계기를 만들고 싶음. 관계 지속/강화 의도',
    possibilities: [{label:'만남 원함',pct:55},{label:'관계 유지 시도',pct:30},{label:'사교적 제안',pct:15}],
    emotions: ['💗 만나고싶음','😊 관계강화'],
    action: '구체적 날짜를 바로 제안하면 성사율이 높아요.',
    confidence: 72,
    replies: [
      {style:'공감',text:'좋아! 이번 주 언제 어때?'},
      {style:'다정',text:'밥 먹자니까 반갑다 :) 금요일 어때?'},
      {style:'유머',text:'밥을 같이 먹자고? 오 드디어 ㅋㅋ 언제?'},
      {style:'썸',text:'좋아! 이번 주 중에 날 잡자 :)'},
    ],
    tip: '밥 먹자는 제안에 바로 날짜를 제안하면 적극성이 전달돼요.',
  },
  {
    keys: ['요즘 어때', '요즘 어떻게 지내', '요즘 잘 지내', '요즘 어때요'],
    relation: ['lover','some','friend'],
    surface: '근황 물어보기',
    hidden: '관심 있거나, 오랜만에 연락 물꼬를 트는 것',
    possibilities: [{label:'진심 관심',pct:50},{label:'대화 시작',pct:35},{label:'만남 전 탐색',pct:15}],
    emotions: ['💗 관심','😊 안부'],
    action: '반갑게 받고 자신의 근황을 나누며 자연스럽게 이어가기.',
    confidence: 70,
    replies: [
      {style:'공감',text:'나쁘지 않아 :) 너는 요즘 어때?'},
      {style:'다정',text:'그럭저럭~ 오랜만에 물어봐줘서 반가워'},
      {style:'유머',text:'요즘? 네 생각하느라 바쁘지 ㅋㅋ 농담이고 잘 지내'},
      {style:'썸',text:'요즘 잘 지내. 너 생각도 했어 :)'},
    ],
    tip: '요즘 어때라고 물어보는 건 관심의 표현이에요. 따뜻하게 받아주세요.',
  },

  /* ── 14. 자주 오해하는 표현 ─────────────────────────────── */
  {
    keys: ['오늘 힘든 일 있었어', '오늘 힘들었어', '오늘 좀 힘들었어'],
    relation: ['lover','some','friend'],
    surface: '하루 힘들었음을 공유',
    hidden: '위로받고 싶고, 들어줄 사람이 필요함',
    possibilities: [{label:'위로 원함',pct:60},{label:'스트레스 해소 원함',pct:30},{label:'단순 공유',pct:10}],
    emotions: ['🥺 위로필요','😔 지침'],
    action: '"많이 힘들었겠다. 뭔 일 있었어?" 하고 먼저 공감해주세요.',
    confidence: 80,
    replies: [
      {style:'공감',text:'많이 힘들었겠다ㅠ 무슨 일 있었어?'},
      {style:'다정',text:'고생했어. 얘기해줘. 들을게'},
      {style:'유머',text:'힘든 날엔 나한테 털어놔야지 ㅎㅎ 뭔데?'},
      {style:'썸',text:'힘들었어? 얘기해봐. 기분 나아지게 해줄게 :)'},
    ],
    tip: '"왜? 뭐 때문에?"보다 공감이 먼저예요.',
  },
  {
    keys: ['그때 왜 그랬어', '그때 일은 왜', '그때 왜 그런 말 했어', '그때 기억해'],
    relation: ['lover','some','friend'],
    surface: '과거 행동에 대한 의문/항의',
    hidden: '아직 정리가 안 된 감정이 있음. 이해받고 싶음',
    possibilities: [{label:'감정 미해결',pct:55},{label:'사과 원함',pct:30},{label:'관계 정리 시도',pct:15}],
    emotions: ['😔 미해결감정','💔 상처'],
    action: '방어하지 말고 "그때 내가 왜 그랬는지 설명할게"로 접근하기.',
    confidence: 76,
    replies: [
      {style:'공감',text:'그때 일 아직 마음에 있었구나. 말해줘서 고마워. 설명할게'},
      {style:'다정',text:'그때 내가 많이 상처 줬던 거 알아. 미안해'},
      {style:'유머',text:'그때 일 기억하는구나 ㅠ 사실 나도 후회해'},
      {style:'썸',text:'그때 내 행동 잘못된 거 알아. 만나서 제대로 얘기하고 싶어'},
    ],
    tip: '과거 일을 꺼내는 건 아직 관계를 포기하지 않은 신호예요.',
  },
  {
    keys: ['보내줄게', '먼저 가', '먼저 자도 돼', '끊을게', '나 먼저 자야겠어'],
    relation: ['lover','some','friend'],
    surface: '대화/자리 마무리',
    hidden: '아쉽지만 먼저 끊어야 하는 상황, 또는 상대 배려',
    possibilities: [{label:'실제 피곤함',pct:45},{label:'배려',pct:35},{label:'대화 부담',pct:20}],
    emotions: ['😴 피곤함','💗 배려'],
    action: '따뜻하게 마무리하고 내일을 예고해두기.',
    confidence: 65,
    replies: [
      {style:'공감',text:'응 쉬어~ 오늘 고생했어'},
      {style:'다정',text:'잘 자. 내일 또 얘기하자 :)'},
      {style:'유머',text:'먼저 자? 꿈에 나 나오면 알려줘 ㅋㅋ 잘 자'},
      {style:'썸',text:'잘 자 :) 내일 또 연락해도 돼?'},
    ],
    tip: '마무리할 때 "내일 또" 한 마디가 연결감을 유지해줘요.',
  }

); // HEARIM_DB.push 끝
})();
